### ISSUE TITLE
avoid fallback to number in xyIntegral

### ISSUE THREAD

**Issue by targos** [mljs/spectra-processing#109]
https://github.com/mljs/spectra-processing/blob/c39ed5daf488aa508be34421bc966d0bdfed3378/src/xy/xyIntegral.ts#L44

Similar to https://github.com/mljs/spectra-processing/commit/5f9aae3e6b959eb77f63b28a52f66fe77bdfe874

**Comment by lpatiny** [comment]
xyCheck allows to specify minLength that would throw an error

https://github.com/mljs/spectra-processing/blob/master/src/xy/xyCheck.ts#L9

**Comment by lpatiny** [comment]
I will do it.
