### ISSUE TITLE
utils/createRandomXArray()

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-processing#124]
Get inspired by https://stackoverflow.com/questions/14058340/adding-noise-to-a-signal-in-python

We should be able to create an array containing random number

As testcase we could use xNoiseStandardDeviation.

@aiday-mar Could you propose an API and options for this new function ?

**Comment by aiday-mar** [comment]
createXArray(mean, standardDeviation, numberOfPoints) uses a normal distribution with the mean and standard deviation given. We can use the marsaglia polar method to calculate the normal distribution.
