### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-processing#144]
In:

https://github.com/mljs/spectra-processing/blob/master/src/x/xMaxIndex.ts
https://github.com/mljs/spectra-processing/blob/master/src/x/xMinIndex.ts

Allow to have the from / to / fromIndex / toIndex like in:

https://github.com/mljs/spectra-processing/blob/master/src/x/xMaxValue.ts

What you would need to do:
- fork the project on your account
- clone the project from your account
- try to add the options
- add test cases
- create a pull request

This is a typescript project and is therefore a little bit different from javascript but I think you could manage.

After cloning the project don't forget:

- `npm i`
- `npx jest --watch`

**Comment by targos** [comment]
This was done in https://github.com/mljs/spectra-processing/pull/145
