### ISSUE TITLE
Rename "monotone" to "monotonic"

### ISSUE THREAD

**Issue by targos** [mljs/spectra-processing#174]
- Change `isMonotone` to `isMonotonic` and make it return a number:
  - `0` -> not monotonic
  - `1` -> monotonic increasing
  - `-1` -> monotonic decreasing
  - For a constant function, I guess we can decide to return `1`?
- Remove `isMonotoneIncreasing` function

**Comment by targos** [comment]
@lpatiny wdyt?

**Comment by lpatiny** [comment]
Closed in https://github.com/mljs/spectra-processing/commit/c672db1bb17b35a7a66aa82221846d79826b0553
