### ISSUE TITLE
version 12.4.0 can not directly used.

### ISSUE THREAD

**Issue by jobo322** [mljs/spectra-processing#193]
I got this error at the moment to install the last version.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/12143935/236653874-beb6139a-5837-40e9-8b96-60c98fec3629.png">

**Comment by targos** [comment]
I think you need at least `"moduleResolution": "node16"` in your tsconfig.

**Comment by jobo322** [comment]
thanks
