### ISSUE TITLE
Dead code or bug in xNoiseSanPlot

### ISSUE THREAD

**Issue by targos** [mljs/spectra-processing#233]
The variables assigned here are not used after the assignment:

https://github.com/mljs/spectra-processing/blob/5cd995e9226968d0a117761921a9d50262ac70c0/src/x/xNoiseSanPlot.ts#L160-L161

/cc @lpatiny @wadjih-bencheikh18 who worked on this code.

**Comment by jobo322** [comment]
I transpile the code from Matlab Damien code. This multiplication appears in the original code but we do not export those initial values. It seems it was my fault
