### ISSUE TITLE
Problem building the documentation

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-processing#81]
With the default action to build the documentation I have the following error:

https://github.com/mljs/spectra-processing/runs/2499211793?check_suite_focus=true#step:3:4

In order to let it work I had to add the following 2 lines

https://github.com/mljs/spectra-processing/commit/2c2cbee01967156ab1a2578ae0f8c6fbe8a3fd02

What am I doing wrong ? I would expect that the default action works.

**Comment by targos** [comment]
Can you try to change the babel config to `babel.config.js` ? I think `.babelrc` is loaded by the documentationjs call.

**Comment by lpatiny** [comment]
The documentation build used to work on this project but rerun the last action fails: https://github.com/cheminfo/jcampconverter/actions/workflows/documentationjs.yml
However if I force to use documentationjs-action v1.0.0 it works correctly. It seems it is related to the update from v1.0.0 to v1.0.1.
Rename the file .babelrc to babel.config.js gives the same result (build documentation failed).

**Comment by targos** [comment]
I know it's related to the update, but I don't want to go back to an old version of the documentation generator :(

**Comment by targos** [comment]
If documentationjs now requires to install the project's dependencies, then so be it. We can revert v1 to v1.0.0 and publish v2.0.0 as a major change on the action, wdyt ?

**Comment by lpatiny** [comment]
Yes for me it is ok.

Or is it possible to add a `npm i` step directly in the documentation action ? 
https://github.com/zakodium/documentationjs-action/blob/main/action.yml

**Comment by targos** [comment]
The new version of the action will do `npm install` if there is no `node_modules` folder.
