### ISSUE TITLE
Migrate project to typescript

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-processing#92]
Before you start please have a loot at:
- https://github.com/cheminfo/generator-cheminfo/blob/main/START.md
- https://github.com/cheminfo/generator-cheminfo/blob/main/ts-migration.md

**Comment by lpatiny** [comment]
Well spline-interpolator is not our package so we can not add easily the types in the package. It is an internal call so I think you may just ignore this error.

**Comment by wadjih-bencheikh18** [comment]
> Well spline-interpolator is not our package so we can not add easily the types in the package. It is an internal call so I think you may just ignore this error.

what about the ml-gsd package?

**Comment by lpatiny** [comment]
Done
