### ISSUE TITLE
Documentation of parameters

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-processing#96]
We are using typedoc to generate the documentation in typescript projects.

When describing a parameter the `-` is mandatory otherwise the description does not appear in the documentation.

You can always check the documentation locally using:
```
npm i --global typedoc
typedoc src/index.ts
```

Example of modified code:

https://github.com/mljs/spectra-processing/commit/8600c201b0b0603bd43bd983013902587b8b3644

Example of resulting help

![image](https://user-images.githubusercontent.com/1484241/145829179-d198e27d-d971-4a21-acaf-ae77de4b164a.png)

@wadjih-bencheikh18 Please could you have a look through all the code to fix similar problems ?

**Comment by wadjih-bencheikh18** [comment]
PR added

**Comment by wadjih-bencheikh18** [comment]
fixed in the last PR
