### ISSUE TITLE
Typedoc and options

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-processing#97]
In order to be able to describe the documentation of optional parameters with their default value we should either describe them 'inline' or create a new type in which we take the name of the method and append 'Options'. Like for example: XFindClosestIndexOptions.

If you have only 1 to 3 options it is possible to describe them inline but otherwise the new type is required. Same is true when the same type is reused in many functions.

Here is an example of inline help:

https://github.com/mljs/spectra-processing/commit/63f3fc9fcb0dc76632d737c4071709ef743ebb4c

And the corresponding result in which we see the default value

![image](https://user-images.githubusercontent.com/1484241/145830073-058c3483-5f48-4621-9abf-ce9018d46611.png)

Please could you go through all the code to fix similar problems ?

**Comment by wadjih-bencheikh18** [comment]
fixed in the last PR

**Comment by lpatiny** [comment]
close by https://github.com/mljs/spectra-processing/commit/0572f5c047ab23ac233a482ff00127c09c811a09
