### ISSUE TITLE
No inline help for parameters

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-processing#98]
I don't know if it is an isolated case but we don't need a help for the property of a parameter that has a specific interface. The help is at the level of the definition of the interface.

Also if we don't have a description of the parameter there is no reason to add an `@param`

https://github.com/mljs/spectra-processing/commit/4c6b59a26bd255a49bab8ff39abb8e330f76993e

@wadjih-bencheikh18 could you have a look if there are similar problems ?

**Comment by wadjih-bencheikh18** [comment]
i think this issue is fixed in the last PR added
